<a href="https://colab.research.google.com/github/sanskarb90/NumPy-Lab_fundamentals-/blob/main/01_Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
list=[2,3,4,5,'7',9]
type(list)
ar=np.array(list,dtype=float)
type(ar)
ar

array([2., 3., 4., 5., 7., 9.])

In [ ]:
a=np.arange(20)
a.reshape(4,5)



ar=np.random.randint(1,100,(5,5))
print(ar)
ar[::]

[[82 19 46 52 27]
 [41 47 28 68 30]
 [79 39 59 78 39]
 [79 73 18 70 45]
 [83 24 35 85 89]]


array([[82, 19, 46, 52, 27],
       [41, 47, 28, 68, 30],
       [79, 39, 59, 78, 39],
       [79, 73, 18, 70, 45],
       [83, 24, 35, 85, 89]])

In [ ]:
m =np.arange(1,21).reshape(4,5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
np.zeros((1,1))

array([[0.]])

In [ ]:
import numpy as np
mat = np.arange(1, 81).reshape(10, 8)
print("Original Matrix:")
print(mat)

sub_matrix = mat[-3:, :2]

print("\nSelected Sub-matrix:")
print(sub_matrix)
mat[-5:-2,-3:]

Original Matrix:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]
 [65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80]]

Selected Sub-matrix:
[[57 58]
 [65 66]
 [73 74]]


array([[46, 47, 48],
       [54, 55, 56],
       [62, 63, 64]])

In [ ]:
mat1=np.array([[3,2,1],[6,5,4]])

In [ ]:
np.arange(10,40,5)

array([10, 15, 20, 25, 30, 35])

In [ ]:
mat2 =np.array([[1,2,3],[4,6,7]])

In [ ]:
mat1*mat2

array([[ 3,  4,  3],
       [24, 30, 28]])

In [ ]:
print(mat1)

[[3 2 1]
 [6 5 4]]


In [ ]:
type(mat1)

numpy.ndarray

In [ ]:
mat1[0,2]

np.int64(1)

In [ ]:
mat1[1,2]

np.int64(4)

In [ ]:
np.linspace(1,1,5)

array([1., 1., 1., 1., 1.])

In [ ]:
mat_1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
type(mat_1)

numpy.ndarray

In [ ]:
np.linspace(0,0,0)

array([], dtype=float64)

In [ ]:
print(mat_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
mat_1[1][-2]

np.int64(5)

In [ ]:
mat_1[2][-3]

np.int64(7)

In [ ]:
mat_1[0]

array([1, 2, 3])

In [ ]:
mat_1[1,-2]

np.int64(5)

In [ ]:
mat_1[2]

array([7, 8, 9])

In [ ]:
mat_1[:,2]

array([3, 6, 9])

In [ ]:
mat_1[0,-2]=777

In [ ]:
mat_1

array([[  1, 777,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [ ]:
mat_1[:,-3]

array([1, 4, 7])

In [ ]:
demo_list = [90,80,0]

In [ ]:
mat_1[-1] = demo_list

In [ ]:
mat_1

array([[  1, 777,   3],
       [  4,   5,   6],
       [ 90,  80,   0]])

In [ ]:
mat_1[:]= 0000

In [ ]:
mat_1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
mat_1=0

In [ ]:
mat_1

0

In [ ]:
np.arange(21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
np.arange(1,21,4)

array([ 1,  5,  9, 13, 17])

In [ ]:
np.arange(0)

array([], dtype=int64)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
import numpy as np
m1=np.array([1,2,3])
m2=np.array([4,5,6])

In [ ]:
np.arange(1,7,1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
m2[2]

np.int64(6)

In [ ]:
m2

array([4, 5, 6])

In [ ]:
m1[0]

np.int64(1)

In [ ]:
m1[1]

np.int64(2)

In [ ]:
m1[2]

np.int64(3)

In [ ]:
m1/m2

array([0.25, 0.4 , 0.5 ])

In [ ]:
m1*m2

array([ 4, 10, 18])

In [ ]:
m1+m2

array([5, 7, 9])

In [ ]:
m1-m2

array([-3, -3, -3])

In [ ]:
m1//m2

array([0, 0, 0])

###Stepwise Slicing

In [ ]:
mat =np.linspace(1,42,42).reshape(7,6)
mat<0

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [ ]:
mat

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35., 36.],
       [37., 38., 39., 40., 41., 42.]])

In [ ]:
mat[:5,:5][::2,:2]

array([[ 1.,  2.],
       [13., 14.],
       [25., 26.]])

In [ ]:
mat[:5,:5][::2,:2]

array([[ 1.,  2.],
       [13., 14.],
       [25., 26.]])

In [ ]:
mat[:5,:5][::2,::2]

array([[ 1.,  3.,  5.],
       [13., 15., 17.],
       [25., 27., 29.]])

In [ ]:
#help(np.linspace)

In [ ]:
mat_A=np.arange(0,100,2).reshape(10,5)
mat_A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [ ]:
mat_A[3:5,:3]

array([[30, 32, 34],
       [40, 42, 44]])

In [ ]:
mat_A[-3:,-2:]

array([[76, 78],
       [86, 88],
       [96, 98]])

In [ ]:
mat_A[::4,1::3]

array([[ 2,  8],
       [42, 48],
       [82, 88]])

In [ ]:
demo_mat2= np.random.randint(0,100,(8,8))
demo_mat2

array([[97, 25, 80, 67, 31, 23, 39, 76],
       [53, 52, 43, 84, 63, 35, 71, 13],
       [49, 32, 92, 83, 44, 98, 74, 17],
       [62,  6,  1, 36, 51, 84, 85, 47],
       [83,  9, 74, 71,  3, 98,  0, 70],
       [61, 20, 12, 75, 78, 84,  0, 79],
       [82, 68,  6, 35, 22, 86, 18, 98],
       [68, 38, 96, 83, 54, 85, 78, 61]])

In [ ]:
demo_mat2[1:-3,::6]

array([[53, 71],
       [49, 74],
       [62, 85],
       [83,  0]])

In [ ]:
demo_mat2[3:5,3:5]

array([[36, 51],
       [71,  3]])

In [ ]:
demo_mat2>50

array([[ True, False,  True,  True, False, False, False,  True],
       [ True,  True, False,  True,  True, False,  True, False],
       [False, False,  True,  True, False,  True,  True, False],
       [ True, False, False, False,  True,  True,  True, False],
       [ True, False,  True,  True, False,  True, False,  True],
       [ True, False, False,  True,  True,  True, False,  True],
       [ True,  True, False, False, False,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True,  True]])

In [ ]:
np.lcm(12,20)

np.int64(60)

In [ ]:
np.sin(2)

np.float64(0.9092974268256817)

In [ ]:
np.deg2rad([2,3,4])

array([0.03490659, 0.05235988, 0.06981317])

In [ ]:
np.log(2)

np.float64(0.6931471805599453)

In [ ]:
my_mat1=np.array([0,1])

In [ ]:
my_mat1

array([0, 1])

In [ ]:
identity_matrix= np.eye(4)

In [ ]:
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
identity_matrix[3]=99

In [ ]:
identity_matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [99., 99., 99., 99.]])

In [ ]:
my_arr= np.ones((3,3))

In [ ]:
my_arr=0

In [ ]:
my_arr

0

In [ ]:
mymat=np.array([[ 0, 1, 2, 3, 4],
[ 5, 6, 7, 8, 9],
[10, 11, 12, 13, 14],
[15, 16, 17, 18, 19],
[20, 21, 22, 23, 24],
[25, 26, 27, 28, 29]])

In [ ]:
mymat[5,3]

np.int64(28)

In [ ]:
arr = np.ones((6,6))
arr[2:5, 2:5] =0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
temp=[1,2,3]
avg=np.mean(temp)
print(avg)

2.0


In [ ]:
avg=np.median(temp)
print(avg)

2.0


In [ ]:
np.zeros((12,14))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10,12))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.eye((5)) #((5)) is shape...

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
mat=np.array([[3,2,1],
         [2,3,4],
          [4,5,6]])

In [ ]:
mat[0:3]

array([[3, 2, 1],
       [2, 3, 4],
       [4, 5, 6]])

In [ ]:
mat[0,-2]

np.int64(2)

In [ ]:
mat[1,-3]

np.int64(2)

In [ ]:
mat[0,-3]

np.int64(3)

In [ ]:
m =np.full((10,8),(10))

In [ ]:
m[0,-2]

np.int64(10)

In [ ]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
m= np.random.seed(2)

In [ ]:
print(m)

None


In [ ]:
slice = arr[0:5].copy()

In [ ]:
mask = (mat > 20) & (mat <= 50)

In [ ]:
print(mask)

[[False False False]
 [False False False]
 [False False False]]


In [ ]:
mat= np.arange(100).reshape(10,10)

In [ ]:
demoele=[-1]

In [ ]:
mat=demoele

In [ ]:
mat

[-1]

In [ ]:
m=np.array([[1,2,3,4],
         [4,5,6,5],
            [7,8,9,0]])
print(m)
m.shape

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 0]]


(3, 4)

In [ ]:
m2=np.array([[1,2,3,4],
             [4,5,6,5],
             [7,8,9,0]])
m2.size

12

In [ ]:
m3=np.array([[[[12,34,67]]]])

m3.ndim

4

In [ ]:
m4=np.array([[111,222,333],
            [444,555,666],
            [777,888,999]])
m4.dtype

dtype('int64')

In [ ]:
arr= np.array([1.2,4.5,7.8])
intiger =arr.astype(int)
intiger.dtype

dtype('int64')

In [ ]:
arr=np.array([34,67,90])
print(arr + 5,arr - 10,arr * 100, arr / 7,arr % 2,arr != 3,arr % 2==0 )

[39 72 95] [24 57 80] [3400 6700 9000] [ 4.85714286  9.57142857 12.85714286] [0 1 0] [ True  True  True] [ True False  True]


In [ ]:
arr2=np.array([45,78,90,67])

In [ ]:
arr2[::3]

array([45, 67])

In [ ]:
arr2[arr2<65] #boolean making condiction True or False

In [ ]:
arr2.reshape(2,2)

In [ ]:
arr3=np.array([56,88,10,78,96,46,35,24,11,44,57,96,56,88,10,78,96,46,35,24,57,96,56,88,10,78,96,46,35,24,57,96,56,88,10,78,96,46,35,24,57,96,56,88,10,78,96,46,35,24,57,96,56,88,10,78,96,46,35,24,57,96,56,88,10,78,96,46,35,24,57,96])
# np.size(arr3)
arr3.reshape(8,9)


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.append(arr1,[1,3,4]))
arr1
print(np.delete(arr1,0))
print(np.split(arr2,3))
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))
print(np.dstack((arr1,arr2)))
print(np.concatenate((arr1,arr2)))

In [ ]:
arr1=np.array([32423,87896,656563,66563,635636,63662346,7773757])
arr2=np.array([32423,87598,469876,895797,759898,89579070,8957896])
result=arr1+arr2
print(result)

[    64846    175494   1126439    962360   1395534 153241416  16731653]


In [ ]:
arr= np.array([[3,4,5],[7,9,10]])
new_arr = np.insert(arr,1,[12,56,89],axis=0)
new_arr2=np.insert(new_arr,2,[56,78,45],axis=1)
new_arr2

In [ ]:
price=np.array([100578,657647,679735,736973])
discount=18
final_price=price-(price*discount/100)
final_price


array([ 82473.96, 539270.54, 557382.7 , 604317.86])

In [ ]:
ar=np.random.randint(2,10,(4,10))
ar

array([[7, 6, 5, 3, 2, 5, 8, 2, 9, 5],
       [3, 5, 7, 5, 9, 9, 2, 3, 6, 9],
       [4, 3, 7, 3, 9, 4, 2, 4, 2, 6],
       [8, 5, 9, 3, 7, 2, 7, 3, 7, 6]])

In [ ]:
ar[1]

array([3, 5, 7, 5, 9, 9, 2, 3, 6, 9])

In [ ]:
ar2=np.random.randn(2,2)
ar2

array([[ 3.2797454 ,  0.97086132],
       [ 1.79259285, -0.42901332]])

In [ ]:
np.unique(ar2)

array([-0.42901332,  0.97086132,  1.79259285,  3.2797454 ])

In [ ]:
np.empty(4)

array([0.42901332, 0.97086132, 1.79259285, 3.2797454 ])

In [ ]:
arrr=np.array([3,4,np.nan,6,np.nan])
np.isnan(arrr)
are=np.nan_to_num(arrr,nan=1776)
are

array([   3.,    4., 1776.,    6., 1776.])

In [ ]:
ar=np.array([23,45,np.inf,56,-np.inf])
np.isinf(ar)
np.nan_to_num(ar,posinf=666,neginf=-777)



array([  23.,   45.,  666.,   56., -777.])

In [ ]:
import numpy as np
arr=np.arange(1,10,3)
type(arr)
arr+2
arr*2
arr-1
arr/2
arr//2
arr==4
arr!=4
arr


ar1=np.arange(10)
print(ar1)
ar2=np.random.randint(1,20,(10))
print(ar2)
ar3=np.array([10,20,30,40,50,60,70,80,90,100])
ar3

[0 1 2 3 4 5 6 7 8 9]
[19 15  2  1  3  9  4 19  2 16]


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.lcm(12,80)

np.int64(240)